package br.com.galgo.testes.recursos_comuns.enumerador;

public enum IdTeste {

	ENVIO_PLCOTA_ARQ("2"), //
	ENVIO_PLCOTA_PORTAL("3"), //
	ENVIO_INFO_ANBIMA_ARQ("15"), //
	ENVIO_INFO_ANBIMA_PORTAL("16"), //
	ENVIO_EXTRATO_ARQ("28"), //
	ENVIO_EXTRATO_PORTAL("29"), //
	ENVIO_POSICAO_ARQ("41"), //

	CONSULTA_PLCOTA_ARQ("6"), //
	CONSULTA_PLCOTA_PORTAL("7"), //
	CONSULTA_INFO_ANBIMA_ARQ("19"), //
	CONSULTA_INFO_ANBIMA_PORTAL("20"), //
	CONSULTA_EXTRATO_ARQ("32"), //
	CONSULTA_EXTRATO_PORTAL("33"), //
	CONSULTA_POSICAO_ARQ("44"), //

	CANCELA_PLCOTA_ARQ("9"), //
	CANCELA_PLCOTA_PORTAL("10"), //
	CANCELA_INFO_ANBIMA_ARQ("22"), //
	CANCELA_INFO_ANBIMA_PORTAL("23"), //
	CANCELA_EXTRATO_ARQ("35"), //
	CANCELA_EXTRATO_PORTAL("36"), //
	CANCELA_POSICAO_ARQ("46"), //

	REENVIO_PLCOTA_ARQ("12"), //
	REENVIO_PLCOTA_PORTAL("13"), //
	REENVIO_INFO_ANBIMA_ARQ("25"), //
	REENVIO_INFO_ANBIMA_PORTAL("26"), //
	REENVIO_EXTRATO_ARQ("38"), //
	REENVIO_EXTRATO_PORTAL("39"), //
	REENVIO_POSICAO_ARQ("48");

	private String id;

	IdTeste(String id) {
		this.id = id;
	}

	public String getId() {
		return id;
	}

}
